{
  "formatVersion": "1.1",
  "component": {
    "group": "su.plo.voice.api",
    "module": "server-proxy-common",
    "version": "2.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.32"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.18"
          }
        },
        {
          "group": "su.plo.config",
          "module": "config",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "su.plo.voice",
          "module": "protocol",
          "version": {
            "requires": "2.1.8"
          }
        },
        {
          "group": "su.plo.voice.api",
          "module": "common",
          "version": {
            "requires": "2.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "server-proxy-common-2.1.8.jar",
          "url": "server-proxy-common-2.1.8.jar",
          "size": 72291,
          "sha512": "d8cf874ad94a5161f81bb3ebcc7afffad744877d87d8dd69ee394ae4e80c0b852b6999496d99bb5f5b290a8eaaf04c76d763a41ef8acb128baef46b36b9cccd0",
          "sha256": "adbc62a270f5eb3f6b8d6e010d56b8c6db33373e76570513b3fcafd8d76ead93",
          "sha1": "97f644a852c611ff6bba19f176c48e6f4bb5e1ee",
          "md5": "4884e85a2b94e5bff0263a71bfa8e9d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.32"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.18"
          }
        },
        {
          "group": "su.plo.config",
          "module": "config",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "su.plo.voice",
          "module": "protocol",
          "version": {
            "requires": "2.1.8"
          }
        },
        {
          "group": "su.plo.voice.api",
          "module": "common",
          "version": {
            "requires": "2.1.8"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "server-proxy-common-2.1.8.jar",
          "url": "server-proxy-common-2.1.8.jar",
          "size": 72291,
          "sha512": "d8cf874ad94a5161f81bb3ebcc7afffad744877d87d8dd69ee394ae4e80c0b852b6999496d99bb5f5b290a8eaaf04c76d763a41ef8acb128baef46b36b9cccd0",
          "sha256": "adbc62a270f5eb3f6b8d6e010d56b8c6db33373e76570513b3fcafd8d76ead93",
          "sha1": "97f644a852c611ff6bba19f176c48e6f4bb5e1ee",
          "md5": "4884e85a2b94e5bff0263a71bfa8e9d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "server-proxy-common-2.1.8-sources.jar",
          "url": "server-proxy-common-2.1.8-sources.jar",
          "size": 36064,
          "sha512": "32f80196355a544c309459c8e30e830822300d3a469db0dee481f6bcfc84f5186c495e2c891ce0d81af9eaed4f91d508723f573d1c8ef1d11903f63cd57b3141",
          "sha256": "036ce58d018041efa3d0b01afa72294822e2be0ee9f9de4d5133b51e386c3b97",
          "sha1": "8dcc63fdf19eef6f120dab610d856d2a7c870d49",
          "md5": "eae10d122db405849140764621a73a32"
        }
      ]
    }
  ]
}
