{
  "formatVersion": "1.1",
  "component": {
    "group": "architectury-plugin",
    "module": "architectury-plugin.gradle.plugin",
    "version": "3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "architectury-plugin.gradle.plugin-3.4-SNAPSHOT.jar",
          "url": "architectury-plugin.gradle.plugin-3.4-SNAPSHOT.jar",
          "size": 153021,
          "sha512": "e20b46ca36eeb0883c18502c34dc0430fe8a9e4755915b6030c49a60c519a1749009a9a0b27453b7635e81d130e64d35624f54388ab0546416aa80764a60ffd4",
          "sha256": "7a540488314e45ce7993e814ebed478468f5704f0a9238fc861f30c5574f4639",
          "sha1": "fd9232a00ccca17f6d1bee66f240789005de85fd",
          "md5": "0a256b7d88a8cbbdaae1f0595c69c201"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext",
          "module": "gradle-idea-ext",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-transformer",
          "version": {
            "requires": "5.2.91"
          }
        },
        {
          "group": "dev.architectury",
          "module": "tiny-remapper",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "architectury-plugin.gradle.plugin-3.4-SNAPSHOT.jar",
          "url": "architectury-plugin.gradle.plugin-3.4-SNAPSHOT.jar",
          "size": 153021,
          "sha512": "e20b46ca36eeb0883c18502c34dc0430fe8a9e4755915b6030c49a60c519a1749009a9a0b27453b7635e81d130e64d35624f54388ab0546416aa80764a60ffd4",
          "sha256": "7a540488314e45ce7993e814ebed478468f5704f0a9238fc861f30c5574f4639",
          "sha1": "fd9232a00ccca17f6d1bee66f240789005de85fd",
          "md5": "0a256b7d88a8cbbdaae1f0595c69c201"
        }
      ]
    }
  ]
}
