modLoader = "javafml"
loaderVersion = "${forge_loader_range}"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "catskinc_remake"
version = "${version}"
displayName = "CatSkinC-Remake"
authors = "Q Team Studio"
description = '''

'''
#logoFile = ""

[[dependencies.catskinc_remake]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.catskinc_remake]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.catskinc_remake]]
modId = "architectury"
mandatory = true
versionRange = "${architectury_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.catskinc_remake]]
modId = "voicechat"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.catskinc_remake]]
modId = "plasmovoice"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.catskinc_remake]]
modId = "figura"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.catskinc_remake]]
modId = "emotecraft"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"
