modLoader = "javafml"
loaderVersion = "${forge_loader_range}"
#issueTrackerURL = ""
license = "GPL-3.0-or-later"

[[mods]]
modId = "catskinc"
version = "${version}"
displayName = "CatSkinC"
authors = "Team CatLab Design"
description = '''

'''
#logoFile = ""

[[dependencies.catskinc]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.catskinc]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.catskinc]]
modId = "architectury"
mandatory = true
versionRange = "${architectury_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.catskinc]]
modId = "voicechat"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.catskinc]]
modId = "plasmovoice"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.catskinc]]
modId = "figura"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.catskinc]]
modId = "emotecraft"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

