{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.architectury",
    "module": "architectury-forge",
    "version": "9.2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "architectury-forge-9.2.14.jar",
          "url": "architectury-forge-9.2.14.jar",
          "size": 599211,
          "sha512": "52b8aea6e07f3115b8cf0dd80607d1ed5620464ebc42ebd0cab4c1ecbecc61319a158ad0405259eecec1f287b1c4798b74941937d8da46f0519c18239cbd9d4d",
          "sha256": "47d5eca3d83aae1ac1d4a70116727715bd7ef4c077d228fee873065cbca94687",
          "sha1": "f48e657815d2e540d63bd162238631ed3c5633d3",
          "md5": "61986f8f450f1aeea016c66bcf4b7101"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "architectury-forge-9.2.14.jar",
          "url": "architectury-forge-9.2.14.jar",
          "size": 599211,
          "sha512": "52b8aea6e07f3115b8cf0dd80607d1ed5620464ebc42ebd0cab4c1ecbecc61319a158ad0405259eecec1f287b1c4798b74941937d8da46f0519c18239cbd9d4d",
          "sha256": "47d5eca3d83aae1ac1d4a70116727715bd7ef4c077d228fee873065cbca94687",
          "sha1": "f48e657815d2e540d63bd162238631ed3c5633d3",
          "md5": "61986f8f450f1aeea016c66bcf4b7101"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "architectury-forge-9.2.14-sources.jar",
          "url": "architectury-forge-9.2.14-sources.jar",
          "size": 437285,
          "sha512": "86490594d7f43cbca02ceaa51b2a48027b2f971d773ea50186ea8d981c69d96eb31e52a9e7f3bcca5dd62ca4cf3b5a451c0aacfda22219aef27e0167373dcd81",
          "sha256": "702f097752fff4644c27fc043ef698a6f2073cb74ab513bf53864d0f1a888ac5",
          "sha1": "f7b24aa4e04c54c34799c0366714dd47f92dbfdc",
          "md5": "621eb95779f2e725546301e308dd440e"
        }
      ]
    }
  ]
}
