{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "neoforge",
    "version": "21.1.219",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-21.1.219-sources.jar",
          "url": "neoforge-21.1.219-sources.jar",
          "size": 1774876,
          "sha512": "14bb4971a3626e3967f333910e1d9a81132bdda79c1291b3b7d11e0fb63b73df3c5046eb666db6d5b3364cdb6990bfc390c53b79df43da1567b7701ce0381fae",
          "sha256": "814983ff6c233935f176a99b10a495cfa37971ffe1a73a6f8b097e893553ca8c",
          "sha1": "0eefeb66da85d5ced69c1d0bc86b8140ddff77c1",
          "md5": "78eced73fad1fa9a2de91c8cf786e1e3"
        }
      ]
    },
    {
      "name": "modDevBundle",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "1.21.1-20240808.144430"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "neoforge-21.1.219-userdev.jar",
          "url": "neoforge-21.1.219-userdev.jar",
          "size": 3978801,
          "sha512": "790bc919186a45bdd46bee5c60c3c75cf80b2356f6052d7c595a99623240d14a2bee8f4a811e3f2ee551abafd8e244c442ccd30f9b6466bf0c518d40df5f06ca",
          "sha256": "69c4eca3c24485825bc20a1db7e2ab941b554cce51cf95462c1df06fcd9cee6b",
          "sha1": "9283d40a6b6bf5d096461ce98b73edca4cb4ca11",
          "md5": "69c2483cbc17c374cf79847865b7eade"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-bundle",
          "version": "21.1.219"
        }
      ]
    },
    {
      "name": "modDevConfig",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "files": [
        {
          "name": "neoforge-21.1.219-moddev-config.json",
          "url": "neoforge-21.1.219-moddev-config.json",
          "size": 10209,
          "sha512": "8c3c1aeb3f144205ee37ae16351baebedc981c4384bc496dd642ca0470b2c73542261c27873474b1e7e88a541e89655465217177755f22f1e99c2030d596dcd2",
          "sha256": "f236f3c956bf90017c790ebd0be9de5502d1f2d603205a89590906e9bd03ad46",
          "sha1": "ef03f2f243dc20164d45e0fbb70bfe3819080a44",
          "md5": "983940e3cba0ce46b7361abe2a53ad84"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-config",
          "version": "21.1.219"
        }
      ]
    },
    {
      "name": "installerJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-21.1.219-installer.jar",
          "url": "neoforge-21.1.219-installer.jar",
          "size": 6961236,
          "sha512": "62b047d95ced148e6b1df0dbb21d16803d1c87090ac4f7e8c8f2be3f46a1b9f74a71db6b1e519aa0c7a0991bb97d5a1f3a8f2df81c06505808b00c7b12bbccc3",
          "sha256": "140df0fa17fd438848051ecfa3d091081515ad12bfe34fa126405037ba01de44",
          "sha1": "832c9404c9305da6096829729bc8a94c0da60087",
          "md5": "93f39a5b9c2bcf08fe0efe604cb1ed96"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-installer",
          "version": "21.1.219"
        }
      ]
    },
    {
      "name": "universalJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-21.1.219-universal.jar",
          "url": "neoforge-21.1.219-universal.jar",
          "size": 3524551,
          "sha512": "1ad84c33b0386947256513a8184177fd574dcfec234b80fa93b25f33feb59c19fe71057b5259525059cc86da80e5f5e286be5d21b8d0449da4f5d34f5b2f0e49",
          "sha256": "a062142f38543701e3d4da385f19e8dd9d76d19625c204e9c0aca22ad491b4fd",
          "sha1": "300c6ecf584eab19b4dca5e69cc2ee68d0d21f1f",
          "md5": "f7a703bed50fb3cf2e6926a38ec85aa4"
        }
      ]
    },
    {
      "name": "changelog",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "changelog"
      },
      "files": [
        {
          "name": "neoforge-21.1.219-changelog.txt",
          "url": "neoforge-21.1.219-changelog.txt",
          "size": 44551,
          "sha512": "8c7d2e276c36c6a6816a6420fbdb182628680406beaa639f3798e0fb19af1db3e06c080a5558c9039471e864e5c4b56556c7f0726079aa7d29a859647f7b5784",
          "sha256": "bcc025e32ff67fccd955d5224c056a0f68115718b7b44eab58db143d6b74a842",
          "sha1": "dc7befe8cc409a78b0f55fd7e0c1ce339f2e22f4",
          "md5": "8a5ba3caed7812941dd2ac68ab2128ff"
        }
      ]
    },
    {
      "name": "modDevApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "4.0.42"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "4.0.42"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "coremods",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "11.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.15.2+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "3.0.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "cpw.mods",
          "module": "bootstraplauncher",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "1.21.1-20240808.144430"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "21.1.219"
        }
      ]
    },
    {
      "name": "modDevRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "4.0.42"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "4.0.42"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "coremods",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "11.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.15.2+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "3.0.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "cpw.mods",
          "module": "bootstraplauncher",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "1.21.1-20240808.144430"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "21.1.219"
        }
      ]
    },
    {
      "name": "modDevModulePath",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external"
      },
      "dependencies": [
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "3.0.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "cpw.mods",
          "module": "bootstraplauncher",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-module-path",
          "version": "21.1.219"
        }
      ]
    },
    {
      "name": "modDevTestFixtures",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "4.0.42"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-test-fixtures",
          "version": "21.1.219"
        }
      ]
    }
  ]
}
