{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.juuxel",
    "module": "unprotect",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "unprotect-1.2.0.jar",
          "url": "unprotect-1.2.0.jar",
          "size": 15968,
          "sha512": "f33155629809a955c7cb2fbb04228918cea28a0487ece1b0deae24184e8fd556c83c687cd374b553ef881ae75beef549be751ac0eda4fa5a2dee134341653722",
          "sha256": "d6b8259d9fcee6d21377e4e1ae0e7fecc2e0d8d2d40d83c020e2ca3dde57ec42",
          "sha1": "49cc229a0469f28fae41593a9537743ac6a951dc",
          "md5": "df82ffc0d26bf74090e98438d97132e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.11.2"
          }
        }
      ],
      "files": [
        {
          "name": "unprotect-1.2.0.jar",
          "url": "unprotect-1.2.0.jar",
          "size": 15968,
          "sha512": "f33155629809a955c7cb2fbb04228918cea28a0487ece1b0deae24184e8fd556c83c687cd374b553ef881ae75beef549be751ac0eda4fa5a2dee134341653722",
          "sha256": "d6b8259d9fcee6d21377e4e1ae0e7fecc2e0d8d2d40d83c020e2ca3dde57ec42",
          "sha1": "49cc229a0469f28fae41593a9537743ac6a951dc",
          "md5": "df82ffc0d26bf74090e98438d97132e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "unprotect-1.2.0-sources.jar",
          "url": "unprotect-1.2.0-sources.jar",
          "size": 11869,
          "sha512": "a1937e08d257396128503aef44cbdfa77d168ae9916879644e44b747b28a1dcfbf3c750ba9026f94b8d4579d469a6741c394b7376a2703f66985b521016ff893",
          "sha256": "4c2782722a09e818ae1efb767b420fd6f824203f9263944511c1e38172ca57a1",
          "sha1": "a64ee133a44e90e45d9be87c838271fae671d874",
          "md5": "985782937a254a5b6fdff170f854a7f3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "unprotect-1.2.0-javadoc.jar",
          "url": "unprotect-1.2.0-javadoc.jar",
          "size": 113720,
          "sha512": "760b96ac7de535c4539643c2433359ef65cab7a4ac2e4ddfbdc0468cf3653a4ac610456d3ef8b6eb63e6a69a9ab532d1f3011f8712ed49edd7c9a9babc8ed999",
          "sha256": "77d069056d2b92f41db339fad8d643be6a49e42a1d156ecf9adbf629cfbc5a4e",
          "sha1": "0e130c58b532c21aee5e833bdc02b926e3bb9383",
          "md5": "cf442ea81947abd6f06aa50c427fe14e"
        }
      ]
    }
  ]
}
