{
  "formatVersion": "1.1",
  "component": {
    "group": "su.plo.slib",
    "module": "api-common",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "api-common-1.1.7.jar",
          "url": "api-common-1.1.7.jar",
          "size": 58790,
          "sha512": "11ffcafc59e241763780c2dc9aad4e8cfe775eda005065de539176ddd07ab12a9a0ba840c97087e4025f41d222dcbad4369a578ae0ec0b848a10edfbc15b55c2",
          "sha256": "6554dc17ba0796a908b81e9b73502dae52f159052c2d8c1e43a0b510095bb735",
          "sha1": "d7a40514d5bf4fe55511281ec310e60e1cbb9090",
          "md5": "b5f0eaa3a3ff910d491f185c0774383d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "api-common-1.1.7.jar",
          "url": "api-common-1.1.7.jar",
          "size": 58790,
          "sha512": "11ffcafc59e241763780c2dc9aad4e8cfe775eda005065de539176ddd07ab12a9a0ba840c97087e4025f41d222dcbad4369a578ae0ec0b848a10edfbc15b55c2",
          "sha256": "6554dc17ba0796a908b81e9b73502dae52f159052c2d8c1e43a0b510095bb735",
          "sha1": "d7a40514d5bf4fe55511281ec310e60e1cbb9090",
          "md5": "b5f0eaa3a3ff910d491f185c0774383d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-common-1.1.7-sources.jar",
          "url": "api-common-1.1.7-sources.jar",
          "size": 21103,
          "sha512": "cecd1415d3e4d04ea3d075c2ef34d5bc3cb500713140c6597e56ae13524f6ed068dc364fb43dc9f4a1506e6af80c1da343bcff3fb33ff30ec0ce12639cbe1cec",
          "sha256": "b93c29c2cbca3c38a7254cf5943d60d813495982b55b9a21ce8847bf96910ca6",
          "sha1": "0d8e1fa276348fc253832e5abc0849e1c5449c7c",
          "md5": "67ea5fe48ce15be30c29a516926690c2"
        }
      ]
    }
  ]
}
