{
  "formatVersion": "1.1",
  "component": {
    "group": "su.plo.voice",
    "module": "protocol",
    "version": "2.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.32"
          }
        }
      ],
      "files": [
        {
          "name": "protocol-2.1.8.jar",
          "url": "protocol-2.1.8.jar",
          "size": 104539,
          "sha512": "8f4e23b66c09b78b6deb8eb49c363cd342caa8924d6273a813d6979abead4db80b5785d81246bc3d3e6c665ce0c56ec3dd06feb46e24a77297c01a7a76498d48",
          "sha256": "d01ed21fcc50a31ff03fb696da06a73dc5d630f0e079ea2b52db6a0c3e8566a6",
          "sha1": "f4f11c9443058bcacc855e775b33808d04af03fd",
          "md5": "07e14a92733a89816c77fd4101415bac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "su.plo.slib",
          "module": "api-common",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.32"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "protocol-2.1.8.jar",
          "url": "protocol-2.1.8.jar",
          "size": 104539,
          "sha512": "8f4e23b66c09b78b6deb8eb49c363cd342caa8924d6273a813d6979abead4db80b5785d81246bc3d3e6c665ce0c56ec3dd06feb46e24a77297c01a7a76498d48",
          "sha256": "d01ed21fcc50a31ff03fb696da06a73dc5d630f0e079ea2b52db6a0c3e8566a6",
          "sha1": "f4f11c9443058bcacc855e775b33808d04af03fd",
          "md5": "07e14a92733a89816c77fd4101415bac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protocol-2.1.8-sources.jar",
          "url": "protocol-2.1.8-sources.jar",
          "size": 52188,
          "sha512": "71504bca52217346fc97dcc8c06f93a77ac5660d8f849a1f28ccfaea74a3991e842d708cafd1070c0fa3dd434748b4f142fee123ba7827f716257707a3293529",
          "sha256": "d1038e820db02ec0d874fd6cca9a028438a417c14e6a3be1b99985030d6a4f84",
          "sha1": "b7956305ea7ed3e96a8f3f2c6c42a9bb692a4fc6",
          "md5": "96a379ce714d5abd6a889157dc6efdb8"
        }
      ]
    }
  ]
}
