{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.architectury",
    "module": "architectury",
    "version": "9.2.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "architectury-9.2.14.jar",
          "url": "architectury-9.2.14.jar",
          "size": 255795,
          "sha512": "afcf2f321866c9fbe02ff00c4524719817d84578102c19405f942b32b03431be7245259b17678aed0de2b52536a103d81e72dcbe8c68052932e572ad9b0c7deb",
          "sha256": "ed856225b534be4b8bceba7577f3495832f652736ed0df50b4c4a7b047feeee9",
          "sha1": "88e48b840fcf6a899fae819094c309c1ce28f2d1",
          "md5": "379367b38487d5249a843ec91403c7b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        }
      ],
      "files": [
        {
          "name": "architectury-9.2.14.jar",
          "url": "architectury-9.2.14.jar",
          "size": 255795,
          "sha512": "afcf2f321866c9fbe02ff00c4524719817d84578102c19405f942b32b03431be7245259b17678aed0de2b52536a103d81e72dcbe8c68052932e572ad9b0c7deb",
          "sha256": "ed856225b534be4b8bceba7577f3495832f652736ed0df50b4c4a7b047feeee9",
          "sha1": "88e48b840fcf6a899fae819094c309c1ce28f2d1",
          "md5": "379367b38487d5249a843ec91403c7b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "architectury-9.2.14-sources.jar",
          "url": "architectury-9.2.14-sources.jar",
          "size": 192745,
          "sha512": "4866a99d882d2b19bf71c4cad00321d06653a48e337f5d06fa49b4c5d7f28250eeb084b5094c052fb631f2468b3d14aad790db10a89fce65cdcc165572e1dcc7",
          "sha256": "c23486c0c8d244a617d6fc66976a1694f644fc1ac63b0d56179820d3b2ef2b1c",
          "sha1": "2e220e5dd7e8a591624ad8ed38c6836c8fa2c947",
          "md5": "80481942d799f018a821fdb6b209ccfe"
        }
      ]
    }
  ]
}
